id: ACBFE0505
title: 'The Ambrosia of Blessings: A Prayer to the Vidyādhara of Unparalleled Kindness,
  Drodül Pawo Dorje'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:35:07.518593
  last_modified_at: 2022-02-28 22:35:07.518623
